### PR TITLE
Fix Pylint in CI

### LINKED ISSUE #607: [BUG]: pylint not running in CI
### Version

1.2rc5

### Which installation method(s) does this occur on?

Source

### Describe the bug.

The CI script is failing to find modified Python files

### Minimum reproducible example

```shell
Change a bunch of Python files
Open a PR
```

### Relevant log output

```
fatal: Not a valid commit name 9e1677b4fea45ba37eb68787e31ba47ba52aa86b
No modified Python files to check
>>>> PASSED: pylint style check
```

### Other/Misc.

_No response_

### Code of Conduct

- [x] I agree to follow the AIQ toolkit Code of Conduct
- [x] I have searched the [open bugs](https://github.com/NVIDIA/NeMo-Agent-Toolkit/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

### PR DESCRIPTION
**Pull request by dagardner-nv**
## Description
* The check stage needs a full checkout in order to determine the modified files in the PR
* Add a work-around for #611 

Closes #607

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/NeMo-Agent-Toolkit/blob/develop/docs/source/resources/contributing.md).
- We require that all contributors "sign-off" on their commits. This certifies that the contribution is your original work, or you have rights to submit it under the same license, or a compatible license.
  - Any contribution which contains commits that are not Signed-Off will not be accepted.
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

### CODE REVIEW

File: ci/scripts/github/common.sh [hunk 1]
```diff
@@ -54,6 +54,10 @@ function create_env() {
 
     UV_SYNC_STDERROUT=$(uv sync --active ${extras[@]} 2>&1)
 
+    # Explicitly filter the warning about multiple packages providing a tests module, work-around for issue #611
+    UV_SYNC_STDERROUT=$(echo "${UV_SYNC_STDERROUT}" | grep -v "warning: The module \`tests\` is provided by more than one package")
```
Comment (mdemoret-nv) [inline ci/scripts/github/common.sh:58]: This should be more generic and match any module. Something like:
```
warning: The module \`.*\` is provided by more than one package
```
